import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import astro from "eslint-plugin-astro";
import jsxA11y from "eslint-plugin-jsx-a11y";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

// Flat config, deliberately the same shape as the other sites in the estate.
// The plugin set and the rule choices are theirs; what differs is only what
// this project actually contains. Keeping them aligned means a lesson learned
// in one repository is a one-line change in the rest, rather than four
// configurations that drifted apart for no reason anybody decided on.
//
// See docs/decisions/2026-08-18-eslint-as-javascript-linter.md.

export default defineConfig(
    // dev/pages-removed-details is generated by dev/remove-details.mjs and is
    // gitignored, so it is not source and is not linted.
    globalIgnores([
        "dist/",
        ".astro/",
        "node_modules/",
        "dev/pages-removed-details/",
    ]),

    js.configs.recommended,
    tseslint.configs.recommended,
    astro.configs.recommended,

    {
        files: ["**/*.{js,ts,tsx,astro}"],
        languageOptions: {
            globals: globals.browser,
        },
        rules: {
            // `_`-prefixed bindings are the escape hatch for deliberately
            // unused ones.
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    argsIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                    caughtErrorsIgnorePattern: "^_",
                },
            ],
        },
    },

    // Accessibility, on both the markup Astro renders and the markup React
    // does. A site is read by screen readers and crawlers as much as by people,
    // and these are the mistakes that stay invisible until then.
    {
        files: ["**/*.{tsx,astro}"],
        plugins: { "jsx-a11y": jsxA11y },
        rules: jsxA11y.flatConfigs.recommended.rules,
    },

    // React islands only. The hooks rules and the Fast Refresh check are
    // meaningless for .astro components, which never re-render on the client.
    {
        files: ["**/*.tsx"],
        plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
        rules: {
            ...reactHooks.configs["recommended-latest"].rules,
            "react-refresh/only-export-components": [
                "warn",
                { allowConstantExport: true },
            ],
        },
    },

    // Config files and the build-time scripts under dev/ run in Node, not the
    // browser.
    {
        files: ["*.config.{js,mjs,ts}", "dev/**/*.{js,mjs,ts}"],
        languageOptions: { globals: globals.node },
    },
);
