name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy to server
              uses: appleboy/ssh-action@v1
              with:
                  host: 62.238.28.179
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /opt/paralx
                      git pull
                      docker compose up --build -d
