name: test-build

on:
    pull_request:
        branches:
            - main

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: build image
              run: docker compose -f docker-compose.local.yml build
